In [7]:
import torch
from torch import tensor

print(torch.__version__)

2.3.1


Yay I've installed Pytorch successfully!

## Python Matrix

we going build a matrix utilizing Python

In [5]:
import random

# matrix = []
# for idx in range(3):
#   inner_list = []
#   for jdx in range(3):
#     inner_list.append(random.random())
#   matrix.append(inner_list)

matrix1 = [[random.random() for _ in range(3)] for _ in range(3)]
matrix2 = [[random.random() for _ in range(2)] for _ in range(3)]

print(f"""
[
 {matrix1[0]}
 {matrix1[1]}
 {matrix1[2]}
]
""")


[
 [0.9460028433966913, 0.9990019274432349, 0.6169841010170758]
 [0.5796213763436179, 0.7240185052969731, 0.008151046428208075]
 [0.4817843640598277, 0.35419852727305545, 0.31394503143559993]
]



### issues with Python matrices

- add
  - iterate through both matrices
  - grab each idx and add it together
  - validating the type for input and writing a default statement in case types don't match
  - I would have to account for an edge case where the shape of both matrices don't match

## What is a tensor?

building tensors and conduct some mathematical operations to visualize the simplicity of tensors

In [14]:
matrix1 = tensor([[1.0, 2.0, 3.0], [5.0, 5.0, 6.0], [7.0, 7.0, 9.0]])
matrix2 = tensor([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0], [3.0, 2.0, 1.0]])

# Element-wise addition
result = matrix1 + matrix2
print(result)


tensor([[10., 10., 10.],
        [11., 10., 10.],
        [10.,  9., 10.]])


- **Reshaping**

In [15]:
print(matrix1)
reshaped_matrix1 = matrix1.view(1,9)
print(reshaped_matrix1)

tensor([[1., 2., 3.],
        [5., 5., 6.],
        [7., 7., 9.]])
tensor([[1., 2., 3., 5., 5., 6., 7., 7., 9.]])


- **Slicing**

In [24]:
mytensor = tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sliced_tensor = mytensor[:2, 1:]
print(sliced_tensor)

tensor([[2, 3],
        [5, 6]])


- **boolean slicing**

In [25]:
boolean_tensor = mytensor[mytensor > 5]
print(boolean_tensor)

tensor([6, 7, 8, 9])


- **Concatenation**

In [35]:
# 's' +'s' == 'ss'
# ['s'] + ['s'] == ['s', 's'] ['ss']
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[5, 6], [7, 8]])
concatenated_tensor = torch.cat((tensor1, tensor2), dim=1)  # Concatenate along rows
print(concatenated_tensor)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


- **Stacking**

In [34]:
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[5, 6], [7, 8]])
print(torch.stack((tensor1, tensor2), dim=1))

tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])


## Tensor Methods

In [75]:
matrix1 = tensor([[1.0, 2.0, 3.0], [5.0, 5.0, 6.0], [7.0, 7.0, 9.0]])
matrix2 = tensor([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0], [3.0, 2.0, 1.0]])
mytensor = tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
tensor1 = tensor([[1, 2], [3, 4]])
tensor2 = tensor([[5, 6], [7, 8]])
randTensor = tensor([
 [0.9460028433966913, 0.9990019274432349, 0.6169841010170758],
 [0.5796213763436179, 0.7240185052969731, 0.008151046428208075],
 [0.4817843640598277, 0.35419852727305545, 0.31394503143559993]
])

# Shape
print(f"Shape: {matrix1.shape}\n")

# Numeric Dim
print(f"Ndim{matrix1.ndim}\n")

# Data Type
print(f"Data Type: {tensor1.dtype}\n")

# Unsqueeze
print(f"{tensor2}")
print(f"Unsqueeze: {tensor2.unsqueeze(0)}\n")

# Ravel
print(f"{tensor1}")
print(f"Ravel: {tensor1.ravel()}\n")

# Split
split_tensors = tensor1.split(1, dim=0)
print(f"Split: {split_tensors}\n")

# Math operands
sum_tensor = matrix1.sum().item()
mean_tensor= matrix1.mean()
max_values, max_idxs = matrix1.max(dim=0)
print(f"""
sum: {sum_tensor}
mean: {mean_tensor}
max_values: {max_values}
max_indexes: {max_idxs}
""")

# Transformation
print(matrix1)
print(f"Transformation: {matrix1.t()}")


Shape: torch.Size([3, 3])

Ndim2

Data Type: torch.int64

tensor([[5, 6],
        [7, 8]])
Unsqueeze: tensor([[[5, 6],
         [7, 8]]])

tensor([[1, 2],
        [3, 4]])
Ravel: tensor([1, 2, 3, 4])

Split: (tensor([[1, 2]]), tensor([[3, 4]]))


sum: 45.0
mean: 5.0
max_values: tensor([7., 7., 9.])
max_indexes: tensor([2, 2, 2])

tensor([[1., 2., 3.],
        [5., 5., 6.],
        [7., 7., 9.]])
Transformation: tensor([[1., 5., 7.],
        [2., 5., 7.],
        [3., 6., 9.]])


## Scenarios

- Normalization
- Broadcasting

In [73]:
# mytensor = tensor([[1.0,2.0], [3.0,4.0]])
# normalize_tensor = (mytensor - mytensor.mean() ) / mytensor.std()
# print(normalize_tensor)

single_view = tensor([
  1.0, 
  2.0, 
  3.0
]) # 1x3

three_view = tensor([
  [1.0], 
  [2.0], 
  [3.0]
]) # 3x1

print(single_view + three_view) # 3x3


tensor([[2., 3., 4.],
        [3., 4., 5.],
        [4., 5., 6.]])
